### PR TITLE
Allow for Configurable Archive Period

### PR DESCRIPTION
**Pull request by tybritten**
For https://github.com/nyaruka/rp-archiver/issues/38. Adds a config item called `ArchiveLength` that defaults to 90 days. 
Tests are updated, but still need to add tests specifically for changing the period

### CODE REVIEW

**Comment by tybritten** [comment]
Ok, added tests for ArchiveLength

**Comment by tybritten** [comment]
We're gonna run this on our side first, but I'd love some eyes on the changes I made to see if anything is wrong

**Comment by tybritten** [comment]
so far, so good. It seems to be handling in-use objects gracefully `level=warning msg="unable to delete broadcast, has messages still" broadcast_id=15552384 msg_count=1 org_id=1`

**Comment by tybritten** [comment]
Ok it completed all its runs and it worked exactly as expected. We used a period of 30 days and it worked fine.

**Comment by tybritten** [comment]
Just an update- still working fine as expected

**Comment by nicpottier** [comment]
Great, thanks, we'll merge in.

**Comment by nicpottier** [comment]
Actually just realized that maybe `ArchiveLength` may not be the best name for this. How do you feel about having that be named `RetentionPeriod` which feels more right? (I can make the change)

**Comment by tybritten** [comment]
I agree with that.

**Pull request merged**
