### PR TITLE
🦬 Big file fixes

### PR DESCRIPTION
**Pull request by rowanseymour**
Apologies for the delay getting to this, but I think this finally addresses https://github.com/nyaruka/rp-archiver/issues/45

- Fix erroring when creating archives bigger than 5GB
- Fix checking S3 uploads so that we always check size, but only check hash for files uploaded as single part

@tybritten, @mzealey please take a look

### CODE REVIEW

**Comment by mzealey** [comment]
So I'm not convinced that this really addresses the issue we see in #87 / #88 - because it seems like if your S3 buckets are encrypted then ETag != MD5. So I think a bypass flag is also needed, although I agree that the size check are a good failsafe to have.

**Comment by tybritten** [comment]
Any reason not to calculate the Etag locally before uploading to retain the same functionality >5GB?

**Comment by rowanseymour** [comment]
@mzealey ahh so I guess it's working for us because we're using SSE-S3 but you're using SSE-KMS? I'm not against adding that flag but obviously not checking any hashes is a little risky.

@tybritten we could lean on https://github.com/peak/s3hash/blob/master/s3hash.go to calculate the ETag.. but will that even be correct if the user is using a different encryption type?

**Comment by mzealey** [comment]
Yes apparently we use KMS. Given that according to the doc referenced in #87, 2 of the 3 options (KMS, and >5gb) DON'T do MD5 (and I can't see any docs to detail what they do use) it seems that a bypass (by default??) would be useful.

**Comment by tybritten** [comment]
That makes sense, IMHO

**Pull request merged**
